name: CI/CD Build and Deploy to Home K8s

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Install Dependencies Natively
        run: |
          composer clear-cache
          COMPOSER_MEMORY_LIMIT=-1 composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Downcase Repository Name
        run: |
          echo "IMAGE_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          driver: docker
          push: true
          no-cache: true
          tags: ghcr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}

  deploy-to-k8s:
    needs: build-and-push
    runs-on: self-hosted

    steps:
      - name: Notify Infrastructure Repo of New Image
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.INFRA_PAT }}
          repository: tudopacu/city_builder-infrastructure
          event-type: update-image
          client-payload: '{"app": "yii2-cms", "image": "ghcr.io/tudopacu/city_builder-cms:${{ github.sha }}"}'