name: CI/CD Build and Deploy to Home K8s

on:
  push:
    branches:
      - master  # This restricts the workflow to only run on pushes to the master branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Downcase Repository Name
        run: |
          echo "IMAGE_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.IMAGE_NAME }}:latest
          allow: network.host
          network: host

  deploy-to-k8s:
    needs: build-and-push
    # Tell GitHub to run this job directly on your home server agent
    runs-on: self-hosted

    steps:
      - name: Deploy Manifest directly to Cluster
        run: |
          # The agent runs commands natively as your user on CityBuilderSrv
          kubectl apply -f ~/k8s/yii2-cms.yaml
          kubectl rollout restart deployment/yii2-cms-deployment